apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gaia-frontend
  template:
    metadata:
      labels:
        app: gaia-frontend
    spec:
      containers:
      - name: gaia-frontend
        image: warpwing/gaia:latest
        ports:
        - containerPort: 8501
