apiVersion: v1
kind: Service
metadata:
  name: gaia-frontend-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 8501
      targetPort: 8501
  selector:
    app: gaia-frontend
